SUPABASE_URL = "https://aybsmnmtcdnswpycdyfb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5YnNtbm10Y2Ruc3dweWNkeWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzODU3MTIsImV4cCI6MjA3OTk2MTcxMn0.Zo68fz-cBWHl01qZJ8EUO_4u_r7VaNTdL6WrhUDyrmg"
